### ISSUE TITLE
[feat] 단체 가입 flow 관련 API 작업

### ISSUE THREAD

**Issue by tkdwns414** [TeamPINGLE/PINGLE-SERVER#23]
## Issue 📌
단체 가입 flow에 필요한 API 작업들을 합니다.

## Todo ✔️
- [x] 단체 이름 검색 API
- [x] 단체 디테일 조회 API
- [x] 단체 가입 API
