### ISSUE TITLE
[refac] 코드리뷰 사항 적용

### ISSUE THREAD

**Issue by Parkjyun** [TeamPINGLE/PINGLE-SERVER#44]
## Issue 📌
 - 복수개의 값을 갖고오는 함수명 list -> 복수형
 - 커스텀 헤더에 X-추가
 - 클래스명, 함수명, 변수명에 포함된 regist -> register로 변경 
## Todo ✔️
- [x] 복수개의 값을 갖고오는 함수명 list -> 복수형
- [x] 커스텀 헤더에 X-추가
- [x] 클래스명, 함수명, 변수명에 포함된 regist -> register로 변경
