### ISSUE TITLE
[feat] 소셜 로그인 + JWT 구현

### ISSUE THREAD

**Issue by tkdwns414** [TeamPINGLE/PINGLE-SERVER#6]
## Issue 📌
유저 인증/인가를 위한 소셜 로그인과 JWT를 구현합니다.

## Todo ✔️
- [ ] 카카오 소셜 로그인 구현
- [ ] 애플 소셜 로그인 구현
- [ ] pingle 서버 accessToken 구현
- [ ] pingle 서버 refreshToken 구현

간이 User Entity(id, provider, serial_id, refreshToken, email 필수), AuthController, AuthService
