### ISSUE TITLE
[fix] user soft delete 관련 설정

### ISSUE THREAD

**Issue by tkdwns414** [TeamPINGLE/PINGLE-SERVER#79]
## Issue 📌
유저만 soft delete하고 삭제된 유저에 대한 처리가 돼 있지 않음
삭제된 유저 + 유저 탈퇴에 로직 추가
`단체`
**1. 단체 개설자**
    → 단체 탈퇴 불가능, 양도 권유
**2. 단체 가입자**
    → 단체 탈퇴 가능

`모임`
**1. 모임 개최자**
    1.1. **개최 예정된 모임**
        → 들어온 신청 전부 취소, 모임 삭제
    1.2. **개최 완료된 모임**
        → 삭제된 유저의 이름은 ‘(알 수 없음)‘으로 표시
**2. 모임 참여자**
    2.1. **참여 예정된 모임**
        → 참여 취소
    2.2 **참여 완료된 모임**
        → 삭제된 유저의 이름은 ‘(알 수 없음)’으로 표시

## Todo ✔️
- [x] 그룹장인 사람은 탈퇴가 불가능 => 400 띄워주세요
- [x] 유저 삭제할 때 유저와 연관된 것들 다 삭제하게 변경
- [ ] 미팅관련 삭제는 미팅 삭제하기의 로직 이용
- [x] 그룹 삭제하기 구현 => 알아서 그룹 가입자 수 조정
- [x] 위의 그룹 탈퇴 플로우 구현
